import os
import pandas as pd
import datetime

class MinisterialOrchestrator:
    """
    The Master AI Agent.
    Synthesizes the outputs of all Swarm Sub-Supervisors into a single, cohesive Ministerial Report.
    """
    def __init__(self, global_scored_network: pd.DataFrame, output_dir: str):
        self.network = global_scored_network
        self.output_dir = output_dir

    def generate_report(self):
        """Extracts KPIs and formats a Markdown report for transport ministries."""
        if self.network.empty:
            print("[Ministerial Orchestrator] Network is empty. Cannot generate report.")
            return

        total_segments = len(self.network)
        mean_s3 = self.network['SpeedSafetyScore'].mean()
        high_risk_mask = self.network['SpeedSafetyScore'] <= 30
        high_risk_count = len(self.network[high_risk_mask])
        pct_high_risk = (high_risk_count / total_segments) * 100 if total_segments > 0 else 0

        # Sub-Supervisor breakdown
        if 'SubSupervisorID' in self.network.columns:
            supervisor_counts = self.network['SubSupervisorID'].value_counts().to_dict()
            supervisor_breakdown = "\n".join([f"- **{sup}**: {cnt:,} segments managed" for sup, cnt in supervisor_counts.items()])
        else:
            supervisor_breakdown = "- *No Sub-Supervisors recorded*"

        # Top 3 most critical segments based on Kinematic Severity
        if 'I_S_norm' in self.network.columns:
            critical_df = self.network[high_risk_mask].sort_values(by='I_S_norm', ascending=False).head(3)
            critical_segments_str = ""
            for idx, row in critical_df.iterrows():
                speed_lim = row.get('SpeedLimit', 'N/A')
                f85 = row.get('F85thPercentileSpeed', 'N/A')
                intervention = row.get('AI_SpeedIntervention', 'None')
                critical_segments_str += f"- **Segment {idx}**: Limit={speed_lim} km/h | 85th={f85} km/h\n  *Recommended Action*: {intervention}\n"
        else:
            critical_segments_str = "- *Kinematic Severity data not available*"

        # Generate Markdown
        date_str = datetime.datetime.now().strftime("%B %d, %Y")
        
        markdown_content = f"""# MaKeNeS Ministerial Output Report
**Date:** {date_str}
**Generated By:** Ministerial Orchestrator (Hierarchical AI Swarm)

## Executive Summary
This report aggregates the microscopic simulation data and safety evaluations across all regional deployments. The system utilized a Hierarchical AI Swarm architecture, combining dynamic Density Clustering (K-Means) with localized LLM Sub-Supervisors to assess kinetic risk and recommend policy interventions.

## Global Key Performance Indicators (KPIs)
- **Total Road Segments Evaluated:** {total_segments:,}
- **Mean Network Speed Safety Score ($S^3$):** {mean_s3:.2f} / 100
- **Segments Requiring Critical Intervention ($S^3 \le 30$):** {high_risk_count:,} ({pct_high_risk:.2f}%)

## AI Swarm Topology Breakdown
The network was managed by the following dynamically spawned Sub-Supervisors:
{supervisor_breakdown}

## High-Priority AI Interventions
Based on the **Kinematic Severity Index ($\\hat{{I}}_S$)** calculations and deep actor-based simulation, the Swarm has flagged the following segments for immediate intervention:

{critical_segments_str}

## Policy Note on Variable Speed Limits (VSL)
*Macro/Micro Alignment Warning:* 
Following deep literature review (Safety in Numbers & Feedback Linearization models), our Urban and Rural Sub-Supervisors have been instructed to exercise extreme caution when recommending Variable Speed Limits (VSLs). Studies indicate that without zero-friction lane discipline, VSLs can trigger chaotic tactical lane-changing, leading to severe capacity drops. 

---
*End of Report.*
"""

        report_path = os.path.join(self.output_dir, "outputs", "reports", "ministerial_report.md")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(markdown_content)
            
        print(f"\n[Ministerial Orchestrator] Successfully generated executive report at: {report_path}")

